cargo-features = ["profile-rustflags"]

[package]
name = "hearth"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
fern = "0.7"
# gix = { version = "0.76.0", default-features = false }

[profile.dev]
debug = "line-tables-only"
incremental = true

[profile.debugging]
inherits = "dev"
debug = false
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[profile.dev.build-override]
opt-level = 0
codegen-units = 16
debug = false # when possible

[profile.release.build-override]
opt-level = 0
codegen-units = 16
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[build]
rustflags = ["-Ccodegen-units=4"]
