[workspace]
resolver = "2"
members = [
  "parser",
  "tokenizer",
  # "interpreter",
]
# default-members=["interpreter"]

[workspace.dependencies] 
parser = { path = "./parser" }
tokenizer = { path = "./tokenizer" }
# interpreter = { path = "./interpreter" }
# vm = { path = "./interpreter/src/vm" }

tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = "0.3.22"
# gix = { version = "0.76.0", default-features = false }
